title: test-docs
description: >-
    Testing cross compatiblity with jekyll assets / themes
    between repositories and user / org pages
url: "daephx.github.io"
remote_theme: SupunKavinda/jekyll-theme-leaf
# remote_theme: rundocs/jekyll-rtd-theme

permalink: :slug

social:
    twitter: daephx
    github: daephx

plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jemoji
